User.create(email: 'admin@test.com', password: 'password', username:'admin')
User.create(email: 'satou@test.com', password: 'password', username:'user2')
User.create(email: 'suzuki@test.com', password: 'password', username:'user3')
User.create(email: 'tanaka@test.com', password: 'password', username:'user4')
User.create(email: 'test@test.com', password: 'password', username:'user5')
